-- CreateTable
CREATE TABLE "imports" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "isFullValid" BOOLEAN NOT NULL,
    "data" TEXT NOT NULL
);
